<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "seminar"
 *
 * Auto generated by Extension Builder 2017-08-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Seminars',
    'description' => 'This Extension shows a list of Seminars including a single view and a list of events',
    'category' => 'plugin',
    'author' => 'Sebastian Wolfertz',
    'author_email' => 'S.Wolfertz@Streit-Online.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
